export const UI_TEXT = {
  nav: {
    dashboard: 'لوحة التحكم',
    practice: 'التمرين',
    vocabulary: 'المفردات',
    exam: 'الامتحان',
    tutor: 'المعلم الذكي',
    analytics: 'التحليلات',
    profile: 'الملف الشخصي',
    leaderboard: 'لوحة المتصدرين',
    settings: 'الإعدادات',
  },
  actions: {
    start: 'ابدأ',
    next: 'التالي',
    previous: 'السابق',
    submit: 'إرسال',
    check: 'تحقق',
    skip: 'تخطي',
    cancel: 'إلغاء',
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    retry: 'إعادة المحاولة',
    goBack: 'العودة',
    viewAll: 'عرض الكل',
    signOut: 'تسجيل الخروج',
    hint: 'تلميح',
  },
  sections: {
    reading: 'الاستيعاب',
    vocabulary: 'المفردات',
    writing: 'الكتابة',
    spelling: 'الإملاء',
  } as const,
  auth: {
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    fullName: 'الاسم الكامل',
    forgotPassword: 'نسيت كلمة المرور؟',
    hasAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟',
    or: 'أو',
    googleLogin: 'تسجيل الدخول بحساب Google',
    sendResetLink: 'إرسال رابط إعادة التعيين',
  },
  fsrs: {
    again: 'مجدداً',
    hard: 'صعب',
    good: 'جيد',
    easy: 'سهل',
  },
  errors: {
    emailRequired: 'البريد الإلكتروني مطلوب',
    emailInvalid: 'البريد الإلكتروني غير صالح',
    passwordMin: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    passwordRequired: 'كلمة المرور مطلوبة',
    passwordMismatch: 'كلمات المرور غير متطابقة',
    nameRequired: 'الاسم مطلوب',
    nameTooShort: 'الاسم قصير جداً',
    genericError: 'حدث خطأ، يرجى المحاولة مرة أخرى',
    notFound: 'الصفحة غير موجودة',
    somethingWrong: 'حدث خطأ ما',
  },
  levels: {
    beginner: 'مبتدئ',
    learner: 'متعلم',
    intermediate: 'متوسط',
    advanced: 'متقدم',
    expert: 'خبير',
    professional: 'محترف',
    legend: 'أسطورة',
  },
  motivational: [
    'كل يوم خطوة نحو هدفك! 🎯',
    'استمر! أنت تتحسن يوماً بعد يوم 💪',
    'الممارسة تصنع الكمال ✨',
    'أنت أقرب مما تعتقد! 🚀',
    'هيا نحقق 120 معاً! 🌟',
  ],
} as const;

export const XP_REWARDS = {
  correctEasy: 5,
  correctMedium: 10,
  correctHard: 15,
  perfectSession: 25,
  dailyLogin: 5,
  vocabReview: 10,
  mockExam: 50,
  streakMilestone7: 50,
  streakMilestone30: 200,
} as const;

export const YAEL_SECTIONS = ['reading', 'vocabulary', 'writing', 'spelling'] as const;
export type YAELSection = (typeof YAEL_SECTIONS)[number];

export const SECTION_WEIGHTS: Record<YAELSection, number> = {
  reading: 0.30,
  vocabulary: 0.30,
  writing: 0.20,
  spelling: 0.20,
};
